[project]
name = "matchrank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nflreadpy>=0.1.4",
    "pandas>=2.3.3",
]
